INCLUDE(${CMAKE_CURRENT_LIST_DIR}/platform.cmake)

IF(${CMAKE_BUILD_TYPE} STREQUAL "Debug")
SET(CRT_TYPE d)
ENDIF(${CMAKE_BUILD_TYPE} STREQUAL "Debug")

SET(METAXXA_TESTS_LIBRARIES
    gtest${CRT_TYPE}
)

SET(METAXXA_TESTS_LINK_DIRECTORIES
    ${CMAKE_CURRENT_LIST_DIR}/../lib/bin/${PLATFORM}
)