SET(METAXXA_TESTS_SOURCES
    tests/main.cpp
    tests/TestFunction.h
    tests/TestIsExplicitlyConstructible.h
    tests/TestIsImplicitlyConstructible.h
    tests/TestMoveFunctionArgumentTypes.h
    tests/TestReferenceWrapper.h
    tests/TestTuple.h
    tests/TestType.h
)