INCLUDE(${CMAKE_CURRENT_LIST_DIR}/util.cmake)
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/include_directories.cmake)
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/libraries.cmake)
INCLUDE(${CMAKE_CURRENT_LIST_DIR}/sources.cmake)

INCLUDE_DIRECTORIES(${METAXXA_TESTS_INCLUDE_DIRECTORIES})
LINK_DIRECTORIES(${METAXXA_TESTS_LINK_DIRECTORIES})
ADD_DEFINITIONS(${METAXXA_TESTS_DEFINITIONS})

INITIALIZE_SOURCE_GROUPS(${METAXXA_TESTS_SOURCES})
ADD_EXECUTABLE(metaxxa-tests ${METAXXA_TESTS_SOURCES})
TARGET_LINK_LIBRARIES(metaxxa-tests ${METAXXA_TESTS_LIBRARIES})